[features]
seeds = false
[programs.devnet]
metaplex_anchor_nft = "4zNQ3rDip2dsdJZxXgqFavaNFsVetdN65DWdFPLm54NE"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/svena/.config/solana/id.json"

[scripts]
test = "yarn test -p ./tsconfig.json -t 1000000"
